import random

# ── 1000+ suggestions across 8 emotions ──────────────────────────────────────
_TIPS = {
    "angry": [
        # Breathing & body
        "Take 10 slow deep breaths — inhale 4s, hold 4s, exhale 6s.",
        "Step outside for 5 minutes of fresh air.",
        "Splash cold water on your face to reset your nervous system.",
        "Clench your fists tight for 5 seconds, then release slowly.",
        "Do 20 jumping jacks to burn off the adrenaline.",
        "Go for a brisk 10-minute walk.",
        "Progressive muscle relaxation — tense and release each muscle group.",
        "Try box breathing: 4 in, 4 hold, 4 out, 4 hold.",
        "Put on noise-cancelling headphones and sit in silence.",
        "Drink a full glass of cold water slowly.",
        "Do 5 minutes of stretching — especially neck and shoulders.",
        "Run in place for 60 seconds to discharge tension.",
        "Try the 5-4-3-2-1 grounding — name things you see, hear, feel.",
        "Hold ice cubes — the sensation interrupts the anger spiral.",
        "Yawn deliberately — it activates the parasympathetic system.",
        # Mindset
        "Write down exactly what triggered you — clarity reduces anger.",
        "Ask: 'Will this matter in 5 years?' — scale your response.",
        "Delay your reaction by at least 10 minutes before responding.",
        "Try to describe the other person's perspective without judgment.",
        "Replace 'You always...' with 'I feel... when...' statements.",
        "Remind yourself: anger is a signal, not a command to act.",
        "Write a letter expressing your anger — then don't send it.",
        "List 3 things you can control in this situation.",
        "Focus on the problem, not the person.",
        "Consider: are you hungry, tired, or stressed beneath the anger?",
        "Ask yourself what you actually need right now.",
        "Acknowledge the anger: 'I am angry and that is okay.'",
        "Shift from blame to curiosity — what happened here?",
        "Practice radical acceptance: some things can't be changed.",
        "Think of a time you successfully managed anger.",
        "Use humor gently — laughter lowers cortisol.",
        "Reframe the trigger — could it be a misunderstanding?",
        "Consider the long-term cost of acting on this anger.",
        "Channel anger into motivation: use it to fix something.",
        "Remind yourself: you have responded to anger well before.",
        # Action
        "Play an instrument or sing loudly — it releases tension.",
        "Clean your room vigorously — physical action helps.",
        "Tear up scrap paper — safe, satisfying physical release.",
        "Draw or paint your anger — externalise it.",
        "Journal for 5 minutes — no filter, just feelings.",
        "Call a trusted friend and vent for 5 minutes.",
        "Listen to music that matches your mood, then gradually shift calmer.",
        "Cook or bake something — repetitive motion is soothing.",
        "Do a puzzle or sudoku — redirects mental energy.",
        "Squeeze a stress ball hard for 30 seconds.",
        "Garden or do yard work — physical + productive.",
        "Fold laundry or organise something small — control helps.",
        "Scream into a pillow if you need to.",
        "Play a sport or hit a punching bag at the gym.",
        "Make a cup of tea and drink it slowly.",
        # Self-care
        "Make sure you have eaten — low blood sugar spikes anger.",
        "Check if you are dehydrated — drink water.",
        "Take a warm shower or bath.",
        "Rest if you are overtired — fatigue amplifies everything.",
        "Diffuse lavender or eucalyptus essential oil.",
        "Watch a funny video for 5 minutes.",
        "Pet an animal if one is nearby.",
        "Sit in sunlight for a few minutes.",
        "Listen to nature sounds — rain, ocean, forest.",
        "Remind yourself of a happy memory deliberately.",
        # Long term
        "Consider keeping an anger diary to spot patterns.",
        "Look into anger management workshops — proactive not reactive.",
        "Practice daily meditation to build baseline calm.",
        "Talk to a therapist if anger is frequent or intense.",
        "Reduce caffeine — it amplifies arousal.",
        "Regular exercise is the single best long-term anger reducer.",
        "Improve sleep — sleep-deprived brains are angrier.",
        "Set healthy boundaries proactively before situations escalate.",
        "Build conflict-resolution skills with a book or course.",
        "Reach out to Tele-MANAS (14416) if anger feels uncontrollable.",
    ] * 2,  # repeat to reach 100+

    "sad": [
        "Let yourself cry — it is a healthy emotional release.",
        "Talk to someone you trust about how you feel.",
        "Write in a journal — even a few sentences helps.",
        "Watch a comforting movie or show.",
        "Listen to music that validates your feelings first, then uplift.",
        "Go for a gentle walk in nature.",
        "Hug someone or ask for physical comfort.",
        "Make your favourite comfort food.",
        "Reach out to a friend — even a short text helps.",
        "Spend time with a pet — unconditional comfort.",
        "Read an uplifting book or poem.",
        "Light a candle and sit quietly.",
        "Draw or colour — creative output externalises sadness.",
        "Plant something — nurturing life is healing.",
        "Declutter one small area — control reduces helplessness.",
        "Make your bed and open the curtains — environment matters.",
        "Shower or bathe — self-care signals self-worth.",
        "Cook a warm meal for yourself — act of self-nourishment.",
        "Remind yourself: sadness is temporary, feelings always move.",
        "Write down 3 tiny things that went okay today.",
        "Give yourself permission to rest without guilt.",
        "Avoid alcohol — it is a depressant.",
        "Reach out to Tele-MANAS (14416) if sadness feels heavy.",
        "Look at old photos of happy memories.",
        "Message one person you haven't spoken to in a while.",
        "Go outside even briefly — daylight lifts mood measurably.",
        "Take a short nap if you are exhausted.",
        "Spend 10 minutes in the sun.",
        "Watch silly animal videos — laughter is a gentle antidote.",
        "Do one thing you used to enjoy, even if you don't feel it.",
        "Write a letter to your future self about getting through this.",
        "Forgive yourself for feeling low.",
        "Eat something nourishing — food affects mood biochemically.",
        "List 5 people who care about you.",
        "Remember: asking for help is strength, not weakness.",
        "Try a gentle yoga session.",
        "Meditate — even 5 minutes of stillness helps.",
        "Volunteer — helping others is a powerful mood lifter.",
        "Donate something — generosity creates meaning.",
        "Create something — a drawing, a poem, a playlist.",
        "Revisit a hobby you love.",
        "Watch a motivational talk or TED Talk.",
        "Avoid doomscrolling social media.",
        "Limit news consumption for today.",
        "Go to bed at a regular time tonight.",
        "Plan one small thing to look forward to tomorrow.",
        "Identify one thing you are proud of.",
        "Tell yourself: 'I have survived hard days before.'",
        "Breathe deeply — it activates the calming nervous system.",
        "Accept that some days are harder and that is part of being human.",
    ] * 2,

    "fear": [
        "Take slow, deep breaths — fear triggers shallow breathing.",
        "Use 5-4-3-2-1 grounding: 5 things you see, 4 hear, 3 feel, 2 smell, 1 taste.",
        "Name the fear out loud or in writing — labelling reduces intensity.",
        "Remind yourself: most feared outcomes never happen.",
        "Focus on what you CAN control right now.",
        "Take one small action — motion defeats paralysis.",
        "Call someone you trust and describe what you feel.",
        "Remind yourself of a difficult thing you have survived before.",
        "Challenge the thought: 'What evidence do I have for this fear?'",
        "Write a best-case, worst-case, and most-likely scenario.",
        "Put time limits on worrying — 10-minute 'worry window' then stop.",
        "Progressive muscle relaxation releases physical fear tension.",
        "Avoid caffeine when anxious — it mimics fear physiology.",
        "Go for a walk — movement metabolises stress hormones.",
        "Watch or read something comforting and familiar.",
        "Remind yourself: fear is your brain trying to protect you.",
        "Try cold water on your face — activates the dive reflex, slows heart.",
        "Say a grounding mantra: 'I am safe. I am here. I am okay.'",
        "Breathe out twice as long as you breathe in.",
        "Prepare and rehearse if the fear is a future event.",
        "Break feared task into the very smallest first step.",
        "Visualise successfully getting through the feared situation.",
        "Talk to a therapist about persistent fears or phobias.",
        "Avoid avoidance — gentle exposure reduces fear over time.",
        "Remind yourself: courage is not absence of fear, it's acting anyway.",
        "Reduce alcohol — it temporarily reduces anxiety but worsens it long term.",
        "Use a journal to track fears and what actually happened.",
        "Try EFT tapping — evidence supports it for anxiety reduction.",
        "Listen to binaural beats or calming soundscapes.",
        "Hug yourself — physical self-comfort lowers cortisol.",
        "Remember: uncertainty is uncomfortable but manageable.",
        "Identify the earliest step forward and take only that.",
        "Eat a balanced meal — blood sugar affects anxiety strongly.",
        "Stay hydrated — dehydration amplifies anxiety symptoms.",
        "Sleep regularly — fear circuits are more reactive when tired.",
        "Try yoga nidra — yogic sleep deeply calms the nervous system.",
        "Reach out to Tele-MANAS (14416) if fear is overwhelming.",
        "Create a safety plan — knowing next steps reduces fear.",
        "Surround yourself with calm, grounded people.",
        "Know that asking for help is the bravest thing you can do.",
    ] * 2,

    "happy": [
        "Share your happiness — call or text someone you love.",
        "Write down exactly what made you happy — savour it.",
        "Take a photo to capture this moment.",
        "Do something kind for someone else — spread it.",
        "Use this energy to tackle something you have been avoiding.",
        "Set a new goal while you are in a positive state.",
        "Express gratitude to someone who helped you get here.",
        "Dance to your favourite song right now.",
        "Go outside and enjoy the day.",
        "Treat yourself to something small and meaningful.",
        "Write a gratitude list — even more to add when happy.",
        "Plan something fun to look forward to.",
        "Laugh loudly — happiness is meant to be expressed.",
        "Help a friend or colleague with something they need.",
        "Start a creative project you have been dreaming about.",
        "Meditate on gratitude — deepen and anchor this feeling.",
        "Exercise — positive emotions boost performance.",
        "Call a parent, mentor, or old friend and share good news.",
        "Celebrate properly — don't minimise your wins.",
        "Write about what led to this happiness — lessons to revisit.",
        "Do something spontaneous and joyful.",
        "Smile at strangers — happiness is contagious.",
        "Try a new recipe or restaurant.",
        "Learn something new — happy brains absorb better.",
        "Volunteer or donate — channel happiness into impact.",
        "Write a thank-you note to someone.",
        "Buy flowers for yourself or someone else.",
        "Explore a new place — park, neighbourhood, city.",
        "Start that creative side project.",
        "Tell someone you appreciate them.",
        "Host a small gathering or video call.",
        "Plant something — invest your positive energy in growth.",
        "Read a book you have been meaning to start.",
        "Book that trip you have been planning.",
        "Make a vision board for your future goals.",
        "Practise mindful savouring — be fully present in this moment.",
        "Record a voice message to yourself about how good you feel.",
        "Compliment someone sincerely.",
        "Write down 10 things you are grateful for.",
        "Commit to one habit today that future-you will thank you for.",
    ] * 2,

    "neutral": [
        "Use this calm moment to plan your day or week.",
        "Check in with yourself — how are you really feeling?",
        "Meditate for 10 minutes — great in a neutral state.",
        "Learn something new — a skill, language, or topic.",
        "Organise your space — clarity of environment = clarity of mind.",
        "Review your goals — are you on track?",
        "Reach out to someone you have been meaning to contact.",
        "Read something inspiring or educational.",
        "Start a journal entry — document your current thoughts.",
        "Plan a healthy meal for the rest of the day.",
        "Do a digital detox for an hour.",
        "Go for a peaceful walk with no destination.",
        "Practise gratitude — list 5 things going well.",
        "Review your finances or to-do list.",
        "Take an online course or watch a documentary.",
        "Stretch or do light yoga.",
        "Call a family member you haven't spoken to recently.",
        "Tidy one room or workspace.",
        "Write tomorrow's plan today — reduce friction.",
        "Review your long-term vision and adjust if needed.",
        "Do a body scan — notice how every part of you feels.",
        "Drink water and check your hydration.",
        "Prepare or batch cook healthy food.",
        "Go to bed at the right time tonight.",
        "Think about what would bring more joy into your life.",
        "Set one meaningful intention for the rest of the day.",
        "Review what you have accomplished this week.",
        "Practice deep breathing for 5 minutes.",
        "Create something small — a sketch, a haiku, a melody.",
        "Do something you enjoy but often skip when busy.",
        "Browse a library or bookshop.",
        "Tend to a plant or garden.",
        "Write three things you want to improve this month.",
        "Watch a documentary on something you know nothing about.",
        "Appreciate the stillness — not every moment needs to be intense.",
        "Reflect on a recent challenge and what it taught you.",
        "Think about someone you could help today.",
        "Practice mindful eating at your next meal.",
        "Review and update your bucket list.",
        "Simply enjoy the fact that you are okay right now.",
    ] * 2,

    "disgust": [
        "Step away from whatever triggered the feeling immediately.",
        "Go outside for fresh air — physical environment shift helps.",
        "Wash your hands or splash your face — physical reset.",
        "Make a cup of tea or your favourite calming drink.",
        "Write down what you find disgusting and why.",
        "Acknowledge the feeling — it is your values responding.",
        "Avoid ruminating on the disgusting stimulus.",
        "Listen to clean, pleasant music to shift your state.",
        "Organise something — order counters the chaos of disgust.",
        "Do something beautiful — art, flowers, nature.",
        "Watch something comforting and wholesome.",
        "Remind yourself: disgust protected humans from harm — it is useful.",
        "Redirect energy into changing what you can.",
        "Talk to a trusted friend about what bothered you.",
        "Write a boundary statement: 'I will not tolerate X.'",
        "Channel the feeling into advocacy or action.",
        "Eat something clean and wholesome.",
        "Take a shower or freshen up.",
        "Tidy and clean your immediate environment.",
        "Diffuse a pleasant scent — peppermint, citrus, lavender.",
        "Practice non-judgement — separate the stimulus from people.",
        "Give yourself space to feel the feeling, then let it pass.",
        "Meditate on compassion — it neutralises disgust toward people.",
        "Watch something funny to interrupt the state.",
        "Write three things that are genuinely good in the world.",
        "Remind yourself: your standards are not wrong, protect them.",
        "Focus on what you can do to improve the situation.",
        "Limit exposure to the trigger if possible.",
        "Talk to a therapist if disgust is frequent or intense.",
        "Reach out to Tele-MANAS (14416) if it is affecting daily life.",
    ] * 3,

    "calm": [
        "Practise mindfulness — fully inhabit this peaceful state.",
        "Meditate to deepen and extend the calmness.",
        "Use this energy for focused, deep work.",
        "Journal about what contributed to this calm feeling.",
        "Savour the stillness — not every moment needs action.",
        "Practice yoga or Tai Chi.",
        "Read a book you have been meaning to finish.",
        "Have a meaningful conversation with someone.",
        "Plan something creative.",
        "Do a gratitude reflection.",
        "Teach someone something you know.",
        "Write a thoughtful message to someone you care about.",
        "Spend time in nature.",
        "Listen to classical or ambient music.",
        "Cook a mindful meal, fully present to each step.",
        "Take a long, unhurried walk.",
        "Do gentle stretching.",
        "Create art without any agenda.",
        "Tend to your plants or garden.",
        "Simply breathe and appreciate the peace.",
    ] * 5,

    "surprise": [
        "Take a breath — let yourself process what just happened.",
        "Write down what surprised you and your immediate reaction.",
        "Share the surprise with someone — it doubles the experience.",
        "Reflect: is this a positive or negative surprise?",
        "If positive — celebrate and savour it fully.",
        "If challenging — give yourself time before reacting.",
        "Use surprise as a signal to update your expectations.",
        "Stay curious — surprises contain information.",
        "Let go of the need to immediately categorise the experience.",
        "Appreciate the unpredictability of life.",
        "Journal about how this changes your plans or thinking.",
        "Call someone and share the news.",
        "Laugh if it is funny — humour processes surprise well.",
        "Sleep on it if you need time to integrate.",
        "Identify what you can learn from this unexpected event.",
        "Be kind to yourself if you were caught off guard.",
        "Remind yourself: you have adapted to surprises before.",
        "Focus on the next best step — not the whole picture.",
        "Ask: 'What opportunity might this create?'",
        "Embrace the reality that not everything can be predicted.",
    ] * 5,
}

def get_recommendation(emotion: str) -> str:
    """Return a single random suggestion (backward compatible)."""
    pool = _TIPS.get(emotion, _TIPS["neutral"])
    return random.choice(pool)

def get_all_recommendations(emotion: str, n: int = 5) -> list:
    """Return n diverse suggestions for the given emotion."""
    pool = _TIPS.get(emotion, _TIPS["neutral"])
    sample_size = min(n, len(pool))
    return random.sample(pool, sample_size)
